name = "mercury-api"
main = "src/index.ts"
compatibility_date = "2025-03-01"

workers_dev = true
routes = [{ pattern = "api.blacktape.org", custom_domain = true }]

[[d1_databases]]
binding = "DB"
database_name = "mercury-db"
database_id = "633adc97-ad49-4e6a-a13f-90ff5c3aa427"
