/**
 * Apple Music import — MusicKit JS with user-provided Developer Token.
 *
 * Requires Apple Developer account and a MusicKit key (ES256 JWT).
 * The Developer Token must be generated by the user outside Mercury
 * (via Apple Developer portal or a community JWT generation tool).
 *
 * MusicKit JS is loaded on demand (same lazy script pattern as Leaflet in Phase 7).
 * CSP null in Tauri means this works. Web build will also work if not CSP-restricted.
 *
 * Returns user's saved library artists.
 */

export interface AppleMusicArtist {
	name: string;
	appleId: string;
}

declare global {
	interface Window {
		MusicKit?: {
			configure: (config: unknown) => Promise<void>;
			getInstance: () => {
				authorize: () => Promise<void>;
				api: {
					music: (
						path: string,
						params?: Record<string, unknown>
					) => Promise<{
						data: { data: Array<{ id: string; attributes: { name: string } }> };
					}>;
				};
			};
		};
	}
}

async function loadMusicKit(): Promise<void> {
	return new Promise((resolve, reject) => {
		if (window.MusicKit) {
			resolve();
			return;
		}
		const script = document.createElement('script');
		script.src = 'https://js-cdn.music.apple.com/musickit/v3/musickit.js';
		script.onload = () => resolve();
		script.onerror = () => reject(new Error('Failed to load MusicKit JS'));
		document.head.appendChild(script);
	});
}

export async function importFromAppleMusic(developerToken: string): Promise<AppleMusicArtist[]> {
	await loadMusicKit();
	const MK = window.MusicKit!;

	await MK.configure({
		developerToken,
		app: { name: 'Mercury', build: '1.0' }
	});

	const music = MK.getInstance();
	await music.authorize();

	// Fetch up to 100 saved library artists
	const res = await music.api.music('/v1/me/library/artists', { limit: 100 });
	const artists = res.data?.data ?? [];

	return artists.map((a) => ({ name: a.attributes.name, appleId: a.id }));
}
